Repository Praxisprojekt2021/praxisprojekt, pull requests merged in 2021-05, with the labels that each got.

#153 I128: Min Max Werte für Inputs / Custom Hover Info Boxen
  frontend/static/css/einzelkomponente.css
  frontend/static/css/process_styles.css
  frontend/static/css/styles.css
  frontend/static/js/helper.js
  frontend/static/js/process-editor.js
Labels: bug, enhancement

#151 I95: Dauerladescreen bei falschen uids in der URL
  frontend/static/js/component-editor.js
  frontend/static/js/dashboard-renderer.js
  frontend/static/js/helper.js
  frontend/static/js/process-editor.js
  frontend/templates/component.html
  frontend/templates/index.html
  frontend/templates/info.html
  frontend/templates/process.html
Labels: bug

#152 I148: Prozess-Seite wird nicht aktualisiert wenn Komponente aus Prozess gelöscht wird
  frontend/static/css/process_styles.css
Labels: bug

#142 I131: null als Prozessrisiko Wert von Startseite entfernen
  frontend/static/js/dashboard-renderer.js
  frontend/static/js/process-editor.js
Labels: cleanup

#157 I109 Auslagern von Tabellenheader Helper Texten (neu)
  frontend/static/content/en.json
  frontend/static/content/table_header_info.json
  frontend/static/js/process-editor.js
Labels: cleanup

#172 I167 missing min / max values
  frontend/static/js/process-editor.js
Labels: enhancement

#177 I114 js code cleanup
  frontend/static/js/component-editor.js
  frontend/static/js/helper.js
  frontend/static/js/process-editor.js
Labels: cleanup

#184 I166 design changes
  frontend/static/css/Info_styles.css
  frontend/static/css/einzelkomponente.css
  frontend/static/css/process_styles.css
  frontend/static/css/styles.css
  frontend/static/js/component-editor.js
  frontend/static/js/helper.js
  frontend/static/js/process-editor.js
  frontend/templates/process.html
Labels: bug, enhancement

#194 Pre release politur
  frontend/static/css/styles.css
  frontend/static/images/logo.png
  frontend/static/js/component-editor.js
  frontend/static/js/dashboard-renderer.js
  frontend/static/js/helper.js
  frontend/static/js/process-editor.js
Labels: enhancement

#197 I196 hotfixes
  frontend/static/js/process-editor.js
  requirements.txt
  unittesting/test_database_handler/test_process_handler.py
Labels: bug
